name: SnoreTracker
options:
  bundleIdPrefix: com.yourname
  deploymentTarget:
    iOS: "15.0"

configs:
  Debug: debug
  Release: release

targets:
  SnoreTracker:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: SnoreTracker
        excludes:
          - "**/*.plist"
    settings:
      configs:
        Debug:
          PRODUCT_NAME: SnoreTracker
          PRODUCT_BUNDLE_IDENTIFIER: com.eddiechan.SnoreTracker
          INFOPLIST_FILE: SnoreTracker/Info.plist
          TARGETED_DEVICE_FAMILY: "1"
          SWIFT_VERSION: "5.9"
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        Release:
          PRODUCT_NAME: SnoreTracker
          PRODUCT_BUNDLE_IDENTIFIER: com.eddiechan.SnoreTracker
          INFOPLIST_FILE: SnoreTracker/Info.plist
          TARGETED_DEVICE_FAMILY: "1"
          SWIFT_VERSION: "5.9"
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
